const languageFiles = {
  english: {
    title: "Alexandr Korobeinikov",
    name: "ALEXANDR",
    surname: "KOROBEINIKOV",
    profession: "Front-End developer",
    contacts: "Contacts",
    education: "Education",
    secondaryProfessionalEducation: "Secondary professional education",
    SPEPlace: "Minsk College of Digital Technologies",
    SPETime: "2017-2021",
    englishCourses: "English courses",
    ECPlace: "Streamline 'English for Teens' course'",
    ECTime: "2018-2019",
    languages: "Languages",
    eng: "English",
    intermediate: "(intermediate+)",
    rus: "Russian",
    native: "(native)",
    bel: "Belarusian",
    upperIntermediate: "(upper-intermediate)",
    cze: "Czech",
    beginner: "(beginner)",
    interests: "Interests",
    airsoft: "Airsoft",
    sevenYears: "(7 years+)",
    archery: "Archery",
    oneYear: "(1 year)",
    music: "Music",
    guitar: "(guitar - 200 hours)",
    books: "Books",
    readed: "(1k+ readed)",
    aboutMe: "About Me",
    switchLang: "Switch Language (russian/poland/english)",
    greeting: "Hello!",
    intro: "Welcome to my website.",
    bigText: `Hi! My name is Alexander and I am 22 years old, was graduated
                from the Faculty of Mechatronics at College of of Digital
                Technologies. At the moment, I'm done attending base course of
                Front-end development. As a Junior Front-End Developer, I
                possess an arsenal of skills in HTML, CSS, JavaScript. Currently
                im improving my skills with React and Typescript. I excel in
                designing and maintaining responsive websites that offer a
                smooth user experience. My expertise lies in crafting dynamic,
                engaging interfaces through writing clean and optimized code and
                utilizing cutting-edge development tools and techniques.`,
    expirience: "Working Experience",
    pcOperator: "Computer Operator",
    pcOperatorTime: "2024 - Now",
    pcOperatorPlace: 'LLC "ИнтерьерАльянс"',
    techSpecialist: "Technical specialist",
    techSpecialistTime: "2023 - 2024",
    techSpecialistPlace: 'LLC "Smart House"',
    equipAdjuster: "Equipment Adjuster",
    equipAdjusterTime: "2021 - 2023",
    equipAdjusterPlace: 'LLC "ATLANT"',
    hSkills: "Hard skills",
    sSkills: "Soft skills",
    sSkillCommunication: "Communication",
    sSkillEmpathy: "Empathy / Emotional Intelligence",
    sSkillSelfAwareness: "Self-Awareness",
    sSkillPatience: "Patience",
    sSkillOpenMindedness: "Open-Mindedness",
    sSkillTimeManagement: "Time Management",
    sSkillAccountability: "Accountability",
    sSkillAdaptability: "Adaptability",
    portfolio: "Projects",
    cumInSoon: "Coming soon...",
  },

  poland: {
    title: "Alexander Korobejnokow",
    name: "ALEXANDER",
    surname: "KOROBEJNOKOW",
    profession: "Front-End developer",
    contacts: "Kontakt",
    education: "Wykształcenie",
    secondaryProfessionalEducation: "Średnie specjalne",
    SPEPlace: "Miński Koledż Technologii Cyfrowe",
    SPETime: "2017-2021",
    englishCourses: "Kursy języka angielskiego",
    ECPlace: "Streamline 'English for Teens' kurs'",
    ECTime: "2018-2019",
    languages: "Znajomość języków",
    eng: "angielski",
    intermediate: "(intermediate+)",
    rus: "rosyjski",
    native: "(native)",
    bel: "Białoruski",
    upperIntermediate: "(upper-intermediate)",
    cze: "Czeski",
    beginner: "(beginner)",
    interests: "Zaiteresowania",
    airsoft: "Airsoft",
    sevenYears: "(7 lat+)",
    archery: "Łucznictwo",
    oneYear: "(1 rok)",
    music: "Muzyka",
    guitar: "(Gitara - 200 godzin)",
    books: "Książki",
    readed: "(przeczytałem 1tys książek)",
    aboutMe: "O mnie",
    switchLang: "Zmień język (russian/poland/english)",
    greeting: "Część",
    intro: "Witam na mojej stronie.",
    bigText: `Jestem Aleksander, mam 22 lata, ukończyłem Miński Koledż Technologii Cyfrowych na kierunku mechatroniki. Obecnie odbyłem kurs podstawowy front end. Jako młodszy deweloper tego kierunku posiadam zakres umiejętności w HTML, CSS, JavaScript. Obecnie rozwijam swoje umiejętności w React i Typescript. Dobrze radzę sobie z projektowaniem i wsparciem adaptacyjnych stron internetowych, które proponują płynne doświadczenie użytkowania. Moje doświadczenie oparte jest na tworzeniu dynamiki, atrakcyjnych interfejsów poprzez napisanie czystego i zoptymalizowanego kodu i skuteczne nowoczesne narzędzia oraz metody opracowywania.`,
    expirience: "Doświadczenie zawodowe",
    pcOperator: "Operator urządzeń elektronicznych ",
    pcOperatorTime: "2024 - teraz ",
    pcOperatorPlace: 'LLC "ИнтерьерАльянс"',
    techSpecialist: "Specjalista techniczny",
    techSpecialistTime: "2023 - 2024",
    techSpecialistPlace: 'LLC "Smart House"',
    equipAdjuster: "Ustawiacz maszyn",
    equipAdjusterTime: "2021 - 2023",
    equipAdjusterPlace: 'LLC "ATLANT"',
    hSkills: "Umiejętności zawodowe",
    sSkills: "Cechy osobowe",
    sSkillCommunication: "Komunikatywność",
    sSkillEmpathy: "Empatia / inteligencja emocjonalna",
    sSkillSelfAwareness: "Samoświadomość",
    sSkillPatience: "Cierpliwość",
    sSkillOpenMindedness: "Otwartość umysłu",
    sSkillTimeManagement: "Zarządzanie czasem",
    sSkillAccountability: "Odpowiedzialność",
    sSkillAdaptability: "Adaptacyjność",
    portfolio: "Projekty",
    cumInSoon: "Niedługo będzie (mam nadzieję)...",
  },
  russian: {
    title: "Александр Коробейников",
    name: "АЛЕКСАНДР",
    surname: "КОРОБЕЙНИКОВ",
    profession: "Фронт-энд разработчик",
    contacts: "Контакты",
    education: "Образование",
    secondaryProfessionalEducation: "Средне-специальное",
    SPEPlace: "Минский Колледж Цифровых Технологий",
    SPETime: "2017-2021",
    englishCourses: "Курсы английского",
    ECPlace: "Streamline 'English for Teens' курс'",
    ECTime: "2018-2019",
    languages: "Языки",
    eng: "Английский",
    intermediate: "(intermediate+)",
    rus: "Русский",
    native: "(native)",
    bel: "Белорусский",
    upperIntermediate: "(upper-intermediate)",
    cze: "Чешский",
    beginner: "(beginner)",
    interests: "Интересы",
    airsoft: "Страйкбол",
    sevenYears: "(7 лет+)",
    archery: "Стрельба из лука",
    oneYear: "(1 год)",
    music: "Музыка",
    guitar: "(гитара - 200 часов)",
    books: "Книги",
    readed: "(1к+ прочитано)",
    aboutMe: "Обо мне",
    switchLang: "Сменить язык (russian/poland/english)",
    greeting: "Дарова ебать!",
    intro: "Добро пожаловать на мой сайт.",
    bigText: `Дарова Ебать! Меня зовут Александр, мне 22 года, получил образование на факультете мехатроники в Минском Колледже Цифровых Технологий. В данный момент, закончил базовый курс Фронт-энд разработки. Как младший разработчик этого направления, я обладаю арсеналом навыков в HTML, CSS, JavaScript. В настоящее время я совершенствую свои навыки с React и Typescript. Я преуспеваю в проектировании и поддержке адаптивных веб-сайтов, которые предлагают плавный пользовательский опыт. Мой опыт заключается в создании динамики, привлекательных интерфейсов посредством написания чистого и оптимизированного кода и эффективных передовых инструментов и методов разработки.`,
    expirience: "Опыт работы",
    pcOperator: "Оператор ЭВМ",
    pcOperatorTime: "2024 - сейча",
    pcOperatorPlace: 'LLC "ИнтерьерАльянс"',
    techSpecialist: "Технический специалист",
    techSpecialistTime: "2023 - 2024",
    techSpecialistPlace: 'LLC "Smart House"',
    equipAdjuster: "Наладчик оборудования",
    equipAdjusterTime: "2021 - 2023",
    equipAdjusterPlace: 'LLC "ATLANT"',
    hSkills: "Профессиональные навыки",
    sSkills: "Личные Качества",
    sSkillCommunication: "Коммуникативность",
    sSkillEmpathy: "Эмпатия / Эмоциональный интеллект",
    sSkillSelfAwareness: "Самосознание",
    sSkillPatience: "Терпение",
    sSkillOpenMindedness: "Открытость мышления",
    sSkillTimeManagement: "Тайм-менеджмент",
    sSkillAccountability: "Ответственность",
    sSkillAdaptability: "Адаптивность",
    portfolio: "Проекты",
    cumInSoon: "Скоро будет (надеюсь)...",
  },
};
let currentLanguage = "english";
const languageSwitcher = document.getElementById("language-switcher");
languageSwitcher.addEventListener("change", function () {
  const selectedLanguage = document.getElementById("language-select").value;
  document.querySelectorAll("*").forEach(function (element) {
    if (
      element.childNodes.length === 1 &&
      element.childNodes[0].nodeType === Node.TEXT_NODE
    ) {
      let currentText = element.textContent.trim();
      console.log(currentText);
      const currentTextKey = Object.keys(
        languageFiles[selectedLanguage]
      ).filter((k) => languageFiles[currentLanguage][k] === currentText);
      //   console.log(currentText);
      if (currentTextKey in languageFiles[currentLanguage]) {
        element.textContent = languageFiles[selectedLanguage][currentTextKey];
        // currentLanguage = languageFiles.selectedLanguage;
      }
    }
  });
  currentLanguage = selectedLanguage;
});
